# Generated by Django 4.1.4 on 2023-02-28 16:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=mainapp.models.content_file_name)),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=155)),
                ('subtitle', models.CharField(max_length=155)),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банер',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name="Ім'я категорії")),
                ('slug', models.SlugField(unique=True)),
                ('vendor_code', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категорії',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('product_code', models.IntegerField(verbose_name='Код продукту')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('new_price', models.IntegerField(blank=True, null=True, verbose_name='Нова ціна')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Опис')),
                ('qty_product', models.IntegerField(blank=True, default=1, null=True, verbose_name='Кількість товару')),
                ('ordered', models.IntegerField(default=0, verbose_name='Замовлено разів')),
                ('popular', models.IntegerField(default=1, verbose_name='Разів переглянуто')),
                ('supplier_product_url', models.URLField(blank=True, null=True, verbose_name='Посилання на товар')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Продукція',
                'verbose_name_plural': 'Продукція',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=22)),
                ('color', models.CharField(default='#eda526', max_length=50)),
                ('background', models.CharField(default='#eda526', max_length=50)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Тег',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name="Ім'я найвищої категорії")),
                ('slug', models.SlugField(unique=True)),
                ('category_icon', models.ImageField(blank=True, null=True, upload_to=mainapp.models.content_file_name)),
            ],
            options={
                'verbose_name': 'Найвища категорія',
                'verbose_name_plural': 'Найвищі категорії',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/product/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
