# Generated by Django 4.1.4 on 2023-02-28 16:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name="Ім'я статті")),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Опис')),
                ('slug', models.SlugField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Інформація у підвалі',
                'verbose_name_plural': 'Інформація у підвалі',
            },
        ),
    ]
