# Generated by Django 4.1.4 on 2023-02-28 16:17

import delivery.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('midl_name', models.CharField(max_length=50, verbose_name='По батькові')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Зміни в замовлені')),
                ('paid', models.BooleanField(default=False, verbose_name='Сплачено')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар до замовлення')),
                ('call_back', models.BooleanField(default=False, verbose_name='Чи передзвонити?')),
                ('status', models.CharField(choices=[('new', 'Нове замовлення'), ('in_progress', 'Замовлення в обробці'), ('is_ready', 'Замовлення готове'), ('completed', 'Замовлення виконано')], default='new', max_length=100, verbose_name='Статус замовлення')),
                ('city', delivery.models.CityField(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.city', verbose_name='City')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('delivery_method', delivery.models.DeliveryMethodField(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverymethod', verbose_name='Delivery method')),
                ('warehouse', delivery.models.WarehouseField(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='mainapp.product')),
            ],
        ),
    ]
